<?php

return array (
  'name' => '欢迎回来！',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'user' => 'APP配置',
    'example' => '代理配置',
    'contribution_page' => '投稿设置',
    'eat_page' => '吃瓜专区',
    'photo_page' => '图片专区',
    'duanwen_page' => '短文专区',
    'wenda_page' => '问答专区',
    'asmr_page' => 'ASMR界面',
    'small_page' => '短视频设置',
    'app_page' => '软件界面',
    'movie_page' => '影视界面',
    'live_page' => '直播界面',
    'ad_set' => '广告栏设置',
    'pay_page' => '支付设置',
    'share_page' => '分享设置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.163.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => 'utksei57dkit@163.com',
  'mail_smtp_pass' => 'bengze4258',
  'mail_verify_type' => '2',
  'mail_from' => 'utksei57dkit@163.com',
  'annou_switch' => '0',
  'pressing_switch' => '0',
  'presbing_switch' => '1',
  'annou_text' => '<p class="MsoNormal"><!--[if !supportLists]--></p><p class="MsoNormal"><!--[if !supportLists]--></p><p class="MsoNormal"><!--[if !supportLists]--></p><p style="widows:1;line-height:1.2;"><span style="color:#003399;"><span style="font-size:16px;"><b>欢迎使用！</b></span></span></p><p style="widows:1;line-height:1.2;"><span style="color:#003399;"><span style="font-size:16px;"><b><br /></b></span></span></p><p style="widows:1;line-height:1.2;"><s></s></p><hr /><p><br /></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><span style="color:#009900;white-space:normal;widows:1;">1、吃瓜每日更新</span></span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><span style="color:#009900;white-space:normal;widows:1;">2、ASMR/学习软件/影视月更</span></span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><span style="color:#009900;white-space:normal;widows:1;">3、付费直播间每晚开放（仅限会员）</span></span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;">4、所有资源一律永不添加任何形式的弹窗/引流水印，以便搬运。</span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><br /></span></p><p style="widows:1;line-height:1.2;"><span style="color:#E56600;"><span style="color:#337FE5;white-space:normal;widows:1;">白嫖党将不再提供任何咨询服务，不定期关闭所有白嫖范围及API</span></span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><br /></span></p><p style="widows:1;line-height:1.2;"><span style="color:#009900;"><span style="color:#E56600;">现永久会员仅需</span><span style="color:#E53333;"><strong>￥<span style="font-size:16px;">2</span></strong></span><span style="color:#E53333;font-size:16px;"><strong>9.90</strong></span><span style="color:#E56600;">，原价</span><s><span style="color:#EE33EE;"><strong>￥<span style="font-size:14px;">399.00</span></strong></span></s></span></p><p style="widows:1;line-height:1.2;"><br /></p><p style="widows:1;line-height:1.2;"><span style="color:#E56600;"><span style="color:#E56600;">仅一杯奶茶钱就能立即拥有，所有功能无限制永久使用</span></span></p>',
  'integral_one' => '0',
  'integral_two' => '100',
  'integral_three' => '200',
  'rebate_one' => '5',
  'rebate_two' => '8',
  'rebate_three' => '15',
  'agent_one' => '90%',
  'agent_two' => '70%',
  'agent_three' => '50%',
  'pay' => '0',
  'website' => '',
  'direct' => '严正声明：平台不提供任何线下活动，任何与主播私加联系方式属于个人行为，造成的任何后果自行承担与本平台无关！',
  'video_prefix' => '',
  'chat' => 'http://online.www.xiaohongshu.mom/index/index/home?visiter_id=&visiter_name=&avatar=&business_id=1&groupid=0&special=1&theme=7571f9',
  'invite_code' => '0',
  'zcs' => '1',
  'gonggao' => '这是测试的代理公告，你可以在APP管理后台任意修改！！！',
  'base_gonggao' => '这里是后台公告123',
  'lookword' => 'https://api.emoao.com/api/60s',
  'movie_notice' => '温馨提示：请勿相信影片中的任何赌博广告内容！晚间为播放高峰期，播放卡顿请耐心等待缓冲或暂停一会儿  ·͜· ♡',
  'movie_notice_switch' => '1',
  'movie_page_notice' => '0000',
  'movie_list_notice_switch' => '0',
  'down_mode' => '0',
  'down_method' => '1',
  'ordinary_tips' => '此应用仅限会员用户可下载',
  'sigin_tips' => '您还未登录，是否前去登录？',
  'detailed_picture' => 'https://dd-static.jd.com/ddimg/jfs/t1/223428/12/12765/293776/62df7981E31ea6640/31adc0ff0dbe466a.jpg',
  'detailed_picture_switch' => '1',
  'video_exhibition' => '1',
  'video_exhibition_object' => '2',
  'publish_display' => '1',
  'movie_list_style' => '2',
  'not_logged_in_img' => '/upload/user/images/new_file/20221115/76fb7338db1b30bd96caa59cdacc0769.png',
  'register_bot_text' => 'Tips：软件为一机一号，请牢记你的账号！',
  'water_data_display' => '1',
  'water_details_data_display' => '1',
  'photo_data_display' => '2',
  'photo_details_data_display' => '1',
  'duanwen_data_display' => '2',
  'duanwen_details_data_display' => '1',
  'wenda_data_display' => '2',
  'wenda_details_data_display' => '1',
  'type_of_pictures' => '3',
  'number_of_pictures' => '3',
  'type_of_water' => '3',
  'type_of_asmr' => '2',
  'notice_of_pictures' => 'APP内所有资源无任何水印，开通会员任意搬！活动期间永久会员仅需19.9元',
  'live_switch_banner' => '2',
  'not_logged_in_avatar' => '/upload/user/images/new_file/20221028/36fb7eee09e9797ab0c438261d2b495c.jpg',
  'ad_column_title' => '坏坏猫',
  'ad_column_subheading' => '为您推荐，精选广告',
  'ad_column_img' => '/upload/user/images/new_file/20221226/a84ceaf64f0080e7aa1e747b6f180791.png',
  'water_details_banner' => '1',
  'duanwen_details_banner' => '0',
  'wenda_details_banner' => '0',
  'page_banner_switch' => '0',
  'player_tips' => '您非受邀用户，暂不可申请认证！',
  'scroll_mode_type' => '2',
  'water_btn_switch' => '1',
  'photo_btn_switch' => '1',
  'duanwen_btn_switch' => '1',
  'wenda_btn_switch' => '1',
  'water_page_tips' => 'Tips：投稿需专员审核通过后决定是否收费，审核通过您即获得对应的投稿积分奖励，可使用积分来兑换VIP；欢迎大家积极投稿，优质内容将以置顶的方式展示。注：平台严禁上传一切含有引流水印广告内容，违者一次警告，二次永久封号处理！',
  'photo_page_tips' => 'Tips：最大支持上传30张图片，要求高清、无水印；灌水、引流者 一次警告，二次永久封号！不可解封，请珍惜您的帐号。',
  'duanwen_page_tips' => 'Tips：短文字数无限制，可发布段子、冷笑话等。禁止发布带有引流水印等广告内容，违者不通过！',
  'wenda_page_tips' => 'Tips：禁止发布带有引流水印等广告内容，违者不通过！',
  'live_game_btn_switch' => '0',
  'live_gift_btn_switch' => '1',
  'pay_confirm_tog' => '<p style="font-family:sans-serif;font-size:15px;white-space:normal;"><span style="color:#E53333;"><strong>付款后请按下方教程取码激活VIP</strong></span></p><p style="font-family:sans-serif;font-size:15px;white-space:normal;"><img src="https://ldbbs.ldmnq.com/bbs/topic/attachment/2022-12/78de3587-cbc9-4359-a2c4-c379fedbb588.jpg" width="400" alt="" height="200" title="" align="" style="font-family:sans-serif;white-space:normal;" /></p><p style="font-family:sans-serif;font-size:15px;white-space:normal;">付款时会多出一点手续费，属于正常现象，请放心支付。</p><p style="font-family:sans-serif;font-size:15px;white-space:normal;">如有疑问请联系在线客服处理</p><p style="font-family:sans-serif;font-size:15px;white-space:normal;"><span style="color:#009900;">PS：若进入的不是支付页面就返回重新再进一次</span></p><p style="font-family:sans-serif;font-size:15px;white-space:normal;"><span style="color:#009900;"><br /></span><span style="color:#009900;"></span></p><hr /><p><br /></p>',
  'pay_countdown_reading' => '10',
  'big_bird_music' => '/upload/user/images/new_file/20221103/6a7169882abbb17f57f31d5fd6f984d0.mp3',
  'extension_share_url' => '你好，欢迎分享！',
  'extension_share_img' => '/upload/user/images/new_file/20221128/3a51ebe2b1b1bcd5e15aad2905466df8.jpg',
  'extension_share_logo' => '/upload/user/images/new_file/20221112/93795f361c4b0040179c2e527e259f8f.png',
  'extension_share_qr_code' => '/upload/user/images/new_file/20221106/ddefabc05d8f7407906ccd7ffd74a53a.png',
  'notice_of_pictures_switch' => '1',
  'photo_details_banner' => '0',
  'movie_rest_list_style' => '2',
  'type_of_movie' => '3',
  'allow_login' => '0',
  'allow_registration' => '0',
  'myopic_state' => '0',
  'type_of_myopic' => '1',
  'myopic_video_previewing' => '<video muted controlslist="nodownload" loop="loop" controls="controls" src="http://damaotou.xiaohongshu.mom/upload/user/images/new_file/20221226/59a6352f599328ad84258aa1a31b2be9.mp4" style="width:100%;height:100%" autoplay="autoplay" webkit-playsinline="" playsinline=""></video>',
);
